agenda_salao/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("paginas.urls")),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('agendamento/', include('agendamento.urls')),
    path('servicos/', include('servicos.urls')),
    path('relatorios/', include('relatorios.urls')),



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from api.views import ServicoViewSet, SalaoViewSet, AgendamentoViewSet, UserViewSet
from rest_framework import routers

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


router = routers.DefaultRouter()
router.register(r'servicos', ServicoViewSet)
router.register(r'saloes', SalaoViewSet)
router.register(r'agendamentos', AgendamentoViewSet)
router.register(r'usuarios', UserViewSet)

urlpatterns = [
   path('', include(router.urls)),
   path('swagger/<format>\.json|\.yaml', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

servicos/urls.py
from django.urls import path

from .views import SalaoCreate, SalaoList, ServicoList, SaloesDetail, SalaoListUser
from .views import ServicosCreate, ServicosUpdate, SalaoUpdate
from .views import ServicosDelete, SalaoDelete

urlpatterns = [
    path('cadastrarServico/', ServicosCreate.as_view(), name="cadastrarServico"),
    path('cadastrarSalao/', SalaoCreate.as_view(), name="cadastrarSalao"),

    path('editarServico/<int:pk>/', ServicosUpdate.as_view(), name="editarServico"),
    path('editarSalao/<int:pk>/', SalaoUpdate.as_view(), name="editarSalao"),

    path('excluirServico/<int:pk>/', ServicosDelete.as_view(), name="excluirServico"),
    path('editarSalao/<int:pk>/', SalaoDelete.as_view(), name="excluirSalao"),

    path('listarSaloes/', SalaoList.as_view(), name="listarSaloes"),
    path('listarSaloesUser/', SalaoListUser.as_view(), name="listarSaloesUser"),
    path('listarServicos/', ServicoList.as_view(), name="listarServicos"),

    path('listarServicosId/<int:pk>', ServicoList.as_view(), name="listarServicosId"),
    path('detalhesSalaoId/<int:pk>', SaloesDetail.as_view(), name="detalhesSalao"),
]

servicos/models.py
from django.db import models
from autoslug import AutoSlugField


class Salao(models.Model):
    nome = models.CharField(max_length=255)
    image = models.ImageField(upload_to="saloes/%Y/%m/%d", blank=True)
    localizacao = models.TextField(verbose_name='Localização')
    responsavel = models.ForeignKey('accounts.User', verbose_name='Responsável', on_delete=models.CASCADE)

    # saloes = models.Manager()

    class Meta:
        verbose_name = "salão"
        verbose_name_plural = "salões"

    def __str__(self):
        return self.nome


class AvailableManager(models.Manager):  # personalizando novo manager
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)  # filtro para serviços disponiveis


class Servico(models.Model):
    nome = models.CharField(max_length=255)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="nome")
    preco = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='preço')
    estabelecimento = models.ForeignKey(Salao, on_delete=models.CASCADE)
    descricao = models.TextField(blank=True, verbose_name='descrição')
    is_available = models.BooleanField(default=True)

    Servicos = models.Manager()  # manager padrão
    available = AvailableManager()  # novo manager

    class Meta:
        verbose_name = "servico"
        verbose_name_plural = "serviços"

    def __str__(self):
        return "{} - {}".format(self.nome, self.preco)

servicos/forms.py
from django.forms import ModelForm

from .models import Servico, Salao


class SalaoForm(ModelForm):
    class Meta:
        model = Salao
        fields = ['nome', 'image', 'localizacao']


class ServicoForm(ModelForm):
    class Meta:
        model = Servico
        fields = "__all__"

servicos/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from .forms import ServicoForm
from .models import Servico, Salao
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin


####### Create #########


class ServicosCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    model = Servico
    group_required = u"Proprietários"
    fields = '__all__'
    template_name = 'servicos/formularioCreate.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super(ServicosCreate, self).get_context_data(**kwargs)
        #estabelecimento = Salao.objects.filter(responsavel= self.request.user)
        #estabelecimentos = [estabelecimento for estabelecimento in Salao.objects.filter(responsavel=self.request.user)]
        context['form'].fields['estabelecimento'].queryset = Salao.objects.filter(responsavel=self.request.user)
        return context


class SalaoCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    model = Salao
    group_required = [u"Proprietários", u"Adminstrador"]
    fields = ['nome', 'image', 'localizacao']
    template_name = 'servicos/formularioCreate.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.responsavel = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


###### Update ######


class ServicosUpdate(LoginRequiredMixin, UpdateView):
    model = Servico
    form_class = ServicoForm
    # fields = ['preco', 'descricao', 'is_available']
    template_name = 'servicos/formularioCreate.html'
    success_url = reverse_lazy('index')


class SalaoUpdate(LoginRequiredMixin, UpdateView):
    model = Salao
    fields = ['nome', 'image', 'localizacao']
    template_name = 'servicos/formularioCreate.html'
    success_url = reverse_lazy('index')


####### Delete #########


class ServicosDelete(LoginRequiredMixin, DeleteView):
    model = Servico
    template_name = 'servicos/formularioDelete.html'
    success_url = reverse_lazy('index')


class SalaoDelete(LoginRequiredMixin, DeleteView):
    model = Salao
    template_name = 'servicos/formularioDelete.html'
    success_url = reverse_lazy('listarSaloes')


####### List #########


class SalaoList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    paginate_by = 6
    model = Salao
    template_name = 'servicos/listarSaloes.html'

    def get_queryset(self):
        return Salao.objects.all().order_by('nome')


class SalaoListUser(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Salao
    template_name = 'servicos/listarSaloesTabela.html'

    def get_queryset(self):
        queryset = Salao.objects.filter(responsavel=self.request.user).order_by('nome')
        return queryset


class ServicoList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Servico
    template_name = 'servicos/listarServicos.html'

    def get_queryset(self):
        queryset = Servico.available.all()
        salao = Salao.objects.filter(responsavel=self.request.user)

        queryset = queryset.filter(estabelecimento__in=salao)
        return queryset


####### Detail #########


class SaloesDetail(DetailView):
    queryset = Salao.objects.all()
    template_name = 'servicos/listarSaloesTabela.html'

    def get_context_data(self, *args, **kwargs):
        context = super(SaloesDetail, self).get_context_data(*args, **kwargs)
        return context

servicos/templates/servicos/formularioCreate.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

{% block title %}Cadastro{% endblock title %}

{% block conteudo %}


<div class="row mb-4 mb-5">
    <div class="col-md-6 mx-auto">
        <h3 class="text-center">Cadastro</h3>

        <hr>
        <form method="post" action="">
            {% csrf_token %}
            {% bootstrap_form form %}

            <button type="submit" class="btn btn-primary botao">Cadastrar</button>

        </form>
    </div>

</div>

{% endblock %}

servicos/templates/servicos/formularioDelete.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Cadastro{% endblock title %}

{% block conteudo %}


<div class="row">
    <div class="col-md-6 mx-auto">
        <h3>Excluir registros</h3>
        <p class="lead">Confirme para excluir</p>

        <hr>
        <form method="post" action="">
            <p>Deseja excluir o registro: {{ object }} ?</p>

            {% csrf_token %}
            {{ form|crispy }}

            <button type="submit" class="btn btn-danger">Excluir</button>

        </form>
    </div>

</div>

{% endblock %}

servicos/templates/servicos/listarSaloes.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% load saloes_tags %}

{% block conteudo %}
<div class="container my-3">
    <div class="row mx-auto">
        <div class="col-lg-9 mx-auto">
            <div class="card-deck mb-3">
                {% for product in salao_list %}
                <div class="card">
                    <a href="{{ product.get_absolute_url }}">
                        {% if product.image %}
                        <img class="card-img-top" src="/media/{{product.image}}" alt="" >
                        {% else %}
                        <img class="card-img-top" src="{% static 'img/no_image.jpg' %}" alt="">
                        {% endif %}
                    </a>

                    <div class="card-body d-flex flex-column justify-content-between">
                        <a class="text-decoration-none " style="color: #c81e5c" href="{{ product.get_absolute_url }}">
                            <h5 class="card-title">{{ product.nome }}</h5>
                        </a>
                        <a href="{% url 'agendamento' product.id %}" class="btn dropdown-item lead mr-4 font-weight-light text-center" style="background-color: #c81e5c; color:#fff">Agendar</a>

                    </div>
                </div>
                {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div>
            <div class="card-deck mb-3">
                {% endif %}
                {% endfor %}

                {% if salao_list|length|remainder == 2 %}
                <div class="card border-0"></div>
                {% elif salao_list|length|remainder == 1 %}
                <div class="card border-0"></div>
                <div class="card border-0"></div>
                {% endif %}
            </div>

            {% if is_paginated %}
            {% include "paginas/pagination.html" with page=page_obj %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock conteudo %}

servicos/templates/servicos/listarSaloesTabela.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block title %}Listar{% endblock title %}

{% block conteudo %}
<div class="row">
    <div class="col-md-8 mx-auto">
        <h3>Lista de Salões</h3>
        <hr>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr>

                    <th scope="col">Nome</th>
                    <th scope="col">Localização</th>
                    <th scope="col" class="text-center"><i class="fas fa-cogs"></i></th>

                </tr>
                </thead>
                <tbody>
                {% if salao_list %}
                {% for salao in salao_list %}
                <tr>

                    <td>{{ salao.nome }}</td>
                    <td>{{ salao.localizacao }}</td>
                    <td class="project-actions text-center">
                        <a class="btn btn-info btn-sm" href="{% url 'editarSalao' salao.id %}">
                            <i class="fas fa-pencil-alt">
                            </i>
                            Editar
                        </a>
                    </td>

                </tr>
                {% endfor %}

                {% else %}
                <tr>
                    <td colspan="4"><i class="fas fa-info" style="color:#4c6ef5"></i> Nenhum Serviço</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

servicos/templates/servicos/listarServicos.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block title %}Listar{% endblock title %}

{% block conteudo %}
<div class="row">
    <div class="col-md-8 mx-auto">
        <h3>Lista de Serviços</h3>
        <hr>
        <div class="table-responsive">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nome</th>
                  <th scope="col">Preço</th>
                  <th scope="col">Descrição</th>

                </tr>
              </thead>
              <tbody>
              {% if servico_list %}
                {% for servico in servico_list %}
                    <tr>
                        <td><input type="checkbox"  id="{{ servico.id }}"></td>
                        <td>{{ servico.nome }}</td>
                        <td>{{ servico.preco }}</td>
                        <td>{{ servico.descricao }}</td>

                    </tr>
                {% endfor %}
                    <tr>

                      <td colspan="4" style="text-align: right;">
                          <button type="button" class="btn btn-info">Agendar</button>
                      </td>

                    </tr>
              {% else %}
                 <tr>
                    <td colspan="4"><i class="fas fa-info" style="color:#4c6ef5"></i> Nenhum Serviço</td>
                 </tr>
              {% endif %}
              </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}